### ISSUE TITLE
Terraform - Create VPC

### ISSUE THREAD

**Issue by digitalsoba** [CSUN-SeniorDesign/matabit-infrastructure#29]
- [x] Subnets

- [x] Route Table

- [x] Internet Gateways

- [x] NAT

- Create NAT instance in a public Subnet with an Elastic IP. 

- EIP of the NAT will be attached to the routing tables of the private subnets as a default route.

**Comment by digitalsoba** [comment]
Reassigned to Anthony

**Comment by digitalsoba** [comment]
Testing VPC in class today (9/12)

**Comment by shahedsalehian** [comment]
Assigned myself to task due to collaboration on VPC terraform task. Helped on identifying SSH bug and setting up cloud-init.
