### ISSUE TITLE
Terraform - Service Infustructure (EC2)

### ISSUE THREAD

**Issue by digitalsoba** [CSUN-SeniorDesign/matabit-infrastructure#30]
- [x] EC2 - Make sure SG in pointed to the NAT SG

- [x] Route53

- [x] User keys instances

**Comment by digitalsoba** [comment]
Reassigned to Mario

**Comment by digitalsoba** [comment]
Added reinforcements @shahedsalehian

**Comment by shahedsalehian** [comment]
added changes to the service_infrastructure in regards to the EC2.
remote state is now correctly being used to read the output statements of the VPC state file.
Also the security group is now correctly set up and the cloudinit file is attached to the EC2 instance.
SSH was successful from Bastion to EC2. 

another EC2 instance in another subnet must be added!

**Comment by digitalsoba** [comment]
DONE
