### ISSUE TITLE
Terraform - State/locking with S3

### ISSUE THREAD

**Issue by digitalsoba** [CSUN-SeniorDesign/matabit-infrastructure#31]
Add S3 Bucket to manage Terraform code

**Comment by digitalsoba** [comment]
Reassigned to Shahed

**Comment by digitalsoba** [comment]
Completed by Shahed Tuesday night. Implemented in his own personal task and shared his implementation with group members. State store in an S3 bucket attached to lock with a DynamoDB

**Comment by shahedsalehian** [comment]
Reference Pull Request #37
