### ISSUE TITLE
IAM

### ISSUE THREAD

**Issue by tcallier** [CSUN-SeniorDesign/matabit-infrastructure#59]
- [x] Create IAM user account for CIRCLECI 
    * USE TERRAFORM FOR THIS
- [x] Least privileges
    * PUT action against S3 Bucket ( You might also need PutObjectAcl )
- [x] Create GET action for EC2 Instance to assign instance role and fetch data from S3
    * AWS CLI/SDK (cron job)

Create IAM Group. Create Policy for PUT against the S3 bucket. Create user, add to group.

**Comment by digitalsoba** [comment]
Branch #68
