### ISSUE TITLE
AWS Service Diagram

### ISSUE THREAD

**Issue by shahedsalehian** [CSUN-SeniorDesign/matabit-infrastructure#6]
Things to consider:
- How many subnets do we have? How are they interconnected?
- Where is the internet gateway?
- Where is the nginx server? How is it routing traffic?
- Whats included in the VPC?
- Which subnet is the EC2 instance in?

**Comment by tcallier** [comment]
created pull request

**Comment by tcallier** [comment]
let me know if diagram looks ok
