### ISSUE TITLE
HashiCorp Packer

### ISSUE THREAD

**Issue by tcallier** [CSUN-SeniorDesign/matabit-infrastructure#61]
- [x] Launch new instance with base AMI (ubuntu)
- [x] Use Ansible to setup config
- [x] Create a new AMI from the launched instance
- [x] Provide AMI ID
- [x] Terraform DataSource to find AMI
- [x] Install DataDog Agent (maybe as part of ansible script???)

**Comment by shahedsalehian** [comment]
I haven't used the DataSource to find the AMI. 
I'm only providing the AMI, it will be the task of whoever is designing the ASG to find the AMI with a datasource.
