### ISSUE TITLE
Site deployment

### ISSUE THREAD

**Issue by tcallier** [CSUN-SeniorDesign/matabit-infrastructure#64]
* Create script to run the following:
    - [x] 1. Check S3 for the latest build ID
    - [x] 2. Check the latest build on the local system
    - [x] 3. If newer version is available, download and unpackage somewhere on the system
    - [x] 4. Point the web server at the new version of the code
    - [x] 5. Gracefully restart the web server to make sure it is serving the new information
    - [x] 6. Clean up an packages or deployments that are no longer needed

* Script should not have credentials inside it

**Comment by digitalsoba** [comment]
Bash script and crontab mixed in with #72
