### ISSUE TITLE
CircleCI

### ISSUE THREAD

**Issue by tcallier** [CSUN-SeniorDesign/matabit-infrastructure#66]
* Circle CI
    - [x] 1) Create config (done)
    - [x] 2) Install hugo on the CI system (done)
    - [x] 3) Run hugo against the blog (done) 
    - [x] 4) Make sure that hugo was successfully run (done)
    - [x] 5) Get sha of current commit (circleci has that! Don’t know how to retrieve)
    - [x] 6) Create tarball of public folder with sha of commit
    - [x] 7) Push tarball to s3
        * Restricted IAM role
    - [x] 8) Update something to tell the instances that there is a new version to retrieve

Setup (1)
Build (2, 3)
Package (4, 5)
Upload (6, 7)

**Comment by digitalsoba** [comment]
Mixed in with #72
