### ISSUE TITLE
AWS Lambda

### ISSUE THREAD

**Issue by Mariokassab92** [CSUN-SeniorDesign/matabit-infrastructure#95]
- [x] Use AWS lambda to do our deployments when a new build is created. 
- [x] Write the Lambda function in either python of Go. 
- [x] Rewrite our cronjob from project 2 to now use AWS lambda based on events in S3. 
- [x] Since packages will no longer be pushed to S3 because we are building container images pushed to AWS ECR, write two files that specify the stage to run in either staging or production. 
- [x] The Lambda should lookup the new tag to run for services in AWS ECS, update/createa new task for the service and make sure the deployment completes.
- [x] Keep source doc of Lambda function in infrastructure repo and should have an automated way to update and deploy the lambda function. 
- [x] Look at adding unit tests to make sure that Lambda function works correctly.

**Comment by digitalsoba** [comment]
#Lambda
